### ISSUE TITLE
Can this plugin send email cancel too ?

### ISSUE THREAD

**Issue by killthegame** [rvola/woo-cancel-abandoned-order#12]
Can this plugin auto send email to customer when order change to cancel.

**Comment by rvola** [comment]
Hello @killthegame 
Not in the plugin directly. WooCommerce does not default email for canceled orders.

This plugin has only one job: to cancel an order after a deadline.

However, you can add scripts for sending email using the '[woo_cao_cancel_order](https://github.com/rvola/woo-cancel-abandoned-order/blob/master/includes/class-cao.php#L172)' action hook which gives the parameter $order_id.

Otherwise you also have the possibility to create a template on WooCommerce for the cancellation of email : https://woocommerce.com/posts/how-to-customize-emails-in-woocommerce/
