### ISSUE TITLE
Stock not increased when order is canceled

### ISSUE THREAD

**Issue by dendyaziz** [rvola/woo-cancel-abandoned-order#15]
This plugin is incredible, free and just works.

I'm using this plugin combined with [Stock Locations for Woocommerce](https://github.com/alexmigf/stock-locations-for-woocommerce).

Once the order is canceled, the stock is returned to the correct location. But unfortunately not increasing the main stock.

![Screen Shot 2021-08-07 at 05 39 00](https://user-images.githubusercontent.com/35209381/128577703-4539376d-90ce-4b21-9ba3-2b3e7685afd4.png)

Do you have any thoughts about this? Sorry if the case is not related.

**Comment by rvola** [comment]
hi @dendyaziz 
thank you for the compliment 🤗
the plugin no longer manages the management of restock after a cancellation because it's woocommerce that takes care of it.
Look in the woocommerce settings that the restock box is checked.  In case there are filters and actions to do code injections "manually"
